Update .gitpod.yml

diff --git a/.gitpod.yml b/.gitpod.yml
--- a/.gitpod.yml
+++ b/.gitpod.yml
@@ -16,18 +16,18 @@ tasks:
           cd vue-frontend && npm install
         ;;
       esac
+      
+    command: |
+          # Check if environment variables are set in https://gitpod.io/variables.
+          echo "Checking if environment variables are set ..."
+          if [ -z ${ADYEN_HMAC_KEY+x} ] || [[ -z ${ADYEN_API_KEY+x} ]] || [[ -z ${ADYEN_CLIENT_KEY+x} ]] || [[ -z ${ADYEN_MERCHANT_ACCOUNT+x} ]]; then
+            echo "Expected environment variables not found. Please set the ADYEN_HMAC_KEY, ADYEN_API_KEY, ADYEN_CLIENT_KEY, ADYEN_MERCHANT_ACCOUNT environment variables and rerun session https://gitpod.io/variables."
+            exit 1
+          fi
 
-command: |
-      # Check if environment variables are set in https://gitpod.io/variables.
-      echo "Checking if environment variables are set ..."
-      if [ -z ${ADYEN_HMAC_KEY+x} ] || [[ -z ${ADYEN_API_KEY+x} ]] || [[ -z ${ADYEN_CLIENT_KEY+x} ]] || [[ -z ${ADYEN_MERCHANT_ACCOUNT+x} ]]; then
-        echo "Expected environment variables not found. Please set the ADYEN_HMAC_KEY, ADYEN_API_KEY, ADYEN_CLIENT_KEY, ADYEN_MERCHANT_ACCOUNT environment variables and rerun session https://gitpod.io/variables."
-        exit 1
-      fi
-
-      # Run the application based on specified $path.
-      echo "Starting application for '$path' in $(pwd)"
-      npm run dev
+          # Run the application based on specified $path.
+          echo "Starting application for '$path' in $(pwd)"
+          npm run dev
 
 ports: 
   - port: 8080
